apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- kustomizeconfig/commonannotations.yaml
- kustomizeconfig/commonlabels.yaml
- kustomizeconfig/nameprefix.yaml
- kustomizeconfig/namereference.yaml
- kustomizeconfig/namespace.yaml
- kustomizeconfig/varreference.yaml
- kustomizeconfig/argo.yaml

resources:
- webhook/cm.yaml
- webhook/gateway.yaml
- webhook/sa.yaml
- webhook/ingress.yaml
- webhook/rbac.yaml

- github/gateway.yaml
- github/sa.yaml
- github/rbac.yaml
- github/sensor.yaml

secretGenerator:
- name: github-access
  env: github-access.properties
  type: Opaque

configMapGenerator:
- name: github-gateway-configmap
  files:
  - go-example-build.properties

###########################
# Kubernetes configuration
###########################

namespace: default