apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-controller
spec:
  selector:
    matchLabels:
      app: sensor-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: sensor-controller
    spec:
      serviceAccountName: argo-events-sa
      containers:
      - name: sensor-controller
        image: argoproj/sensor-controller:v0.7
        env:
          - name: SENSOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SENSOR_CONFIG_MAP
            value: $(SENSOR_CONTROLLER_CM)

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-controller
spec:
  selector:
    matchLabels:
      app: gateway-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-controller
    spec:
      serviceAccountName: argo-events-sa
      containers:
      - name: gateway-controller
        image: argoproj/gateway-controller:v0.7
        env:
          - name: GATEWAY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GATEWAY_CONTROLLER_CONFIG_MAP
            value: $(GATEWAY_CONTROLLER_CM)