apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- cm.yaml
- crd.yaml
- deployment.yaml
- rbac.yaml
- sa.yaml

vars:
- name: SENSOR_CONTROLLER_CM
  objref:
    kind: ConfigMap
    name: sensor-controller
    apiVersion: v1
- name: GATEWAY_CONTROLLER_CM
  objref:
    kind: ConfigMap
    name: gateway-controller
    apiVersion: v1