apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- cm.yaml
- crd.yaml
- deployments.yaml
- rbac.yaml
- rbac-aggregates.yaml
- sa.yaml
- service.yaml
- ingress.yaml

vars:
- name: WORKFLOW_CONTROLLER_CM
  objref:
    kind: ConfigMap
    name: workflow-controller-configmap
    apiVersion: v1